name: Export Repository Secrets

on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: List secrets in the repository
        run: |
          gh secret list --repo $GITHUB_REPOSITORY

      - name: Retrieve and export secrets to .env file
        run: |
          echo "NODE_ENV=production" > .env
          gh secret list --repo $GITHUB_REPOSITORY | awk '{print $1}' | while read secret_name; do
            secret_value=$(gh secret get $secret_name --repo $GITHUB_REPOSITORY)
            echo "${secret_name}=${secret_value}" >> .env
            echo "${secret_name}=${secret_value}" >> $GITHUB_ENV  # Export the secret to the environment
          done
