name: Migrate changes

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true # Ensure the PR was merged

    env: # Set all secrets as environment variables
      NODE_ENV: production
      # Automatically inject all secrets with `secrets.*` syntax
      ${GITHUB_ENV}: ${{ toJSON(secrets) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run generate
        run: npm run generate
