name: Migrate changes

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install -y jq
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Export all secrets dynamically to .env file
        run: |
          echo "NODE_ENV=production" > .env
          gh secret list --repo $GITHUB_REPOSITORY | awk '{print $1}' | while read secret_name; do
            secret_value=$(gh secret get $secret_name --repo $GITHUB_REPOSITORY)
            echo "${secret_name}=${secret_value}" >> .env
            echo "${secret_name}=${secret_value}" >> $GITHUB_ENV  # Dynamically adding to workflow environment
          done

      - name: Install dependencies
        run: npm install

      - name: Run generate
        env:
          NODE_ENV: production
        run: node -r dotenv/config src/generate.ts
